a=input("Enter first number : ")
b=input("Enter second number : ")
sum=int(a)+int(b)
a=int(sum)-int(a)
print("First number after swapping : ")
print(a)
b=int(sum)-int(b)
print("Second number after swapping : ")
print(b)
